import {afterEach,describe,expect,it,vi} from 'vitest'
import {cleanup,render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {QueryClient,QueryClientProvider} from '@tanstack/react-query'
import {MemoryRouter} from 'react-router-dom'
import App from './App'
afterEach(()=>{cleanup();vi.restoreAllMocks()})
function renderApp(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter><App/></MemoryRouter></QueryClientProvider>)}
describe('IdentityMesh app',()=>{it('renders secure login after an unauthenticated session check',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:false,status:401,headers:new Headers(),json:async()=>({error:{code:'UNAUTHENTICATED',message:'Authentication is required.'}})}));renderApp();expect(await screen.findByRole('heading',{name:'Sign in to IdentityMesh'})).toBeInTheDocument();expect(screen.getByText(/HttpOnly cookies/)).toBeInTheDocument()});it('submits login and shows assurance overview',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce({ok:false,status:401,headers:new Headers(),json:async()=>({error:{code:'UNAUTHENTICATED'}})}).mockResolvedValueOnce({ok:true,status:200,headers:new Headers(),json:async()=>({csrfToken:'csrf',user:{id:'u1',email:'admin@example.test',displayName:'Demo Owner',roles:['OWNER']}})}).mockResolvedValueOnce({ok:true,status:200,headers:new Headers(),json:async()=>({People:5,ConnectedSystems:3,KnownIdentities:8,ActiveIdentities:4,OrphanAccounts:1,UnresolvedIdentities:1,TerminatedWithActive:1,PrivilegedAccounts:1,OffboardingsInProgress:0,OffboardingsFailed:0,RecentlyVerified:1,ConnectorsDegraded:0,AccessReviewsOverdue:0})});vi.stubGlobal('fetch',fetchMock);renderApp();const password=await screen.findByLabelText('Password');await userEvent.type(password,'correct-horse-battery');await userEvent.click(screen.getByRole('button',{name:/Sign in/}));expect(await screen.findByRole('heading',{name:'Identity Assurance Overview'})).toBeInTheDocument();expect(screen.getByText('Orphan accounts')).toBeInTheDocument()})})
