apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identitymesh
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - availability.yaml
  - network-policy.yaml
images:
  - name: ghcr.io/thiagomontozo/identitymesh-backend
    newTag: latest
  - name: ghcr.io/thiagomontozo/identitymesh-frontend
    newTag: latest
